import React,{useEffect,useMemo,useState} from "react";
import {Edit3,Trash2,Plus,Eye,ArrowLeft} from "lucide-react";
const API=import.meta.env.VITE_API_URL||"http://127.0.0.1:8000/api";
async function req(path,opts={}){
 const token=localStorage.getItem("aiqpg_token");const h={...(opts.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(opts.headers||{})};
 if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(API+path,{...opts,headers:h});const d=await r.json().catch(()=>({}));
 if(!r.ok)throw Error(d.detail||"Request failed");return d
}
const empty={name:"",code:"",department:"CSE",semester:"",academic_year:"2026-27",credits:4,description:""};
export default function Subjects(){
 const[list,setList]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[selected,setSelected]=useState(null),[query,setQuery]=useState(""),[dept,setDept]=useState("All"),[sem,setSem]=useState("All"),[msg,setMsg]=useState("");
 const load=()=>req("/subjects").then(setList).catch(e=>setMsg(e.message));useEffect(load,[]);
 const filtered=useMemo(()=>list.filter(s=>(!query||(s.name+" "+s.code).toLowerCase().includes(query.toLowerCase()))&&(dept==="All"||s.department===dept)&&(sem==="All"||s.semester===sem)),[list,query,dept,sem]);
 const save=async()=>{try{const url=editing?`/subjects/${editing}`:"/subjects";await req(url,{method:editing?"PUT":"POST",body:JSON.stringify({...form,credits:Number(form.credits)})});setMsg(editing?"Subject updated successfully":"Subject created successfully");setForm(empty);setEditing(null);setShow(false);load()}catch(e){setMsg(e.message)}};
 const del=async id=>{if(!window.confirm("Delete this subject?"))return;try{await req(`/subjects/${id}`,{method:"DELETE"});setMsg("Subject deleted.");load();if(selected?.id===id)setSelected(null)}catch(e){setMsg(e.message)}};
 if(selected)return <div className="panel"><button className="back-btn" onClick={()=>setSelected(null)}><ArrowLeft size={16}/> Back to Subjects</button><div className="subject-detail"><span className="code">{selected.code}</span><h1>{selected.name}</h1><p>{selected.description||"No description added."}</p><div className="detail-grid">{[["Department",selected.department],["Semester",selected.semester],["Academic Year",selected.academic_year],["Credits",selected.credits],["Subject ID",selected.id]].map(x=><div className="detail"><span>{x[0]}</span><b>{x[1]||"—"}</b></div>)}</div><div className="detail-grid">{[["Syllabus",selected.syllabus_count||0],["Questions",selected.question_count||0],["Blueprints",selected.blueprint_count||0],["Papers",selected.paper_count||0],["Status","Active"]].map(x=><div className="detail" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><h2>Subject Workspace</h2><div className="workspace-grid">{["Syllabus Analyzer","Question Bank","Blueprint Designer","Previous Paper Analyzer","AI Paper Generator","Answer Key Generator","Paper Vault"].map(x=><div className="workspace-card" key={x}><b>{x}</b><span>Continue with {selected.name}</span></div>)}</div></div></div>;
 const departments=["All",...new Set(list.map(x=>x.department).filter(Boolean))],semesters=["All",...new Set(list.map(x=>x.semester).filter(Boolean))];
 return <div className="panel"><div className="module-head"><div><span className="eyebrow">ACADEMIC</span><h1>Subjects</h1><p>Create, search, filter, open, edit and delete subjects.</p></div><button className="primary" onClick={()=>{setForm(empty);setEditing(null);setShow(true)}}><Plus size={16}/> Add Subject</button></div>{msg&&<div className="notice">{msg}</div>}
 <div className="filter-row"><input className="search" placeholder="Search by subject name or code…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={dept} onChange={e=>setDept(e.target.value)}>{departments.map(x=><option key={x}>{x}</option>)}</select><select value={sem} onChange={e=>setSem(e.target.value)}>{semesters.map(x=><option key={x}>{x}</option>)}</select></div>
 {show&&<div className="form-card"><h3>{editing?"Edit Subject":"Add New Subject"}</h3><div className="form-grid">{Object.keys(empty).map(k=><Field key={k} label={k.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())}><input value={form[k]} onChange={e=>setForm({...form,[k]:k==="credits"?Number(e.target.value):e.target.value})}/></Field>)}</div><div className="actions"><button className="primary" onClick={save}>Save Subject</button><button className="secondary" onClick={()=>setShow(false)}>Cancel</button></div></div>}
 <div className="subject-grid">{filtered.map(s=><div className="subject-card" key={s.id}><div><span className="code">{s.code}</span><h3>{s.name}</h3><p>{s.department} · Semester {s.semester} · {s.credits} credits</p><small>{s.academic_year}</small></div><div className="card-actions"><button title="Open" onClick={async()=>{try{setSelected(await req(`/subjects/${s.id}`))}catch{setSelected(s)}}}><Eye size={16}/></button><button title="Edit" onClick={()=>{setForm({...empty,...s});setEditing(s.id);setShow(true)}}><Edit3 size={16}/></button><button title="Delete" onClick={()=>del(s.id)}><Trash2 size={16}/></button></div></div>)}{!filtered.length&&<Empty/>}</div></div>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty(){return <div className="empty">No subjects found. Click <b>Add Subject</b> to create the first subject.</div>}
